
--Crear table space
CREATE TABLESPACE MID_TERM DATAFILE 'parcial1.dbf' SIZE 50M ;

--Crear usuario
CREATE USER CMARINAL IDENTIFIED BY A12345 DEFAULT TABLESPACE MID_TERM QUOTA 20M ON MID_TERM;


--Crear perfil DBA y acceso y crear tablas
GRANT DBA TO CMARINAL;
GRANT CREATE SESSION, CREATE TABLE TO CMARINAL;
GRANT CONNECT, RESOURCE TO CMARINAL;

--Punto 4

 create sequence COMUNAS_SEQ
  start with 50
  increment by 3
  maxvalue 999999
  minvalue 50;

 create sequence COLEGIOS_SEQ 
  start with 100
  increment by 1
  maxvalue 999999
  minvalue 100;

--Crear tabla comunas

CREATE TABLE COMUNAS (
	ID INTEGER PRIMARY KEY,
	NOMBRE VARCHAR2(255)
);

INSERT INTO COMUNAS VALUES (1,	'POPULAR');
INSERT INTO COMUNAS VALUES (10,	'LA CANDELARIA');
INSERT INTO COMUNAS VALUES (11,	'LAURELES ESTADIO');
INSERT INTO COMUNAS VALUES (12,	'LA AMERICA');
INSERT INTO COMUNAS VALUES (13,	'SAN JAVIER');
INSERT INTO COMUNAS VALUES (14,	'POBLADO');
INSERT INTO COMUNAS VALUES (15,	'GUAYABAL');
INSERT INTO COMUNAS VALUES (16,	'BELÉN');
INSERT INTO COMUNAS VALUES (2,	'SANTA CRUZ');
INSERT INTO COMUNAS VALUES (3,	'MANRIQUE');
INSERT INTO COMUNAS VALUES (4,	'ARANJUEZ');
INSERT INTO COMUNAS VALUES (5,	'CASTILLA');
INSERT INTO COMUNAS VALUES (50,	'PALMITAS');
INSERT INTO COMUNAS VALUES (6,	'DOCE DE OCTUBRE');
INSERT INTO COMUNAS VALUES (60,	'SAN CRISTOBAL');
INSERT INTO COMUNAS VALUES (7,	'ROBLEDO');
INSERT INTO COMUNAS VALUES (70,	'ALTAVISTA');
INSERT INTO COMUNAS VALUES (8,	'VILLA HERMOSA');
INSERT INTO COMUNAS VALUES (80,	'SAN ANTONIO DE PRADO');
INSERT INTO COMUNAS VALUES (9,	'BUENOS AIRES');
INSERT INTO COMUNAS VALUES (90,	'SANTA ELENA');

--Creacion tabla colegios
create table colegios (
    ID INTEGER PRIMARY KEY,
	consecutivo_dane VARCHAR2(255),
	nombre_sede VARCHAR2(255),
	tipo_sede VARCHAR2(255),
	comuna_id INTEGER,
	prestacion_servicio VARCHAR2(255),
	zona VARCHAR2(255),
	barrio VARCHAR2(255),
	sector VARCHAR2(255),
	direccion_sede VARCHAR2(255),
	telefono_sede VARCHAR2(255),
	rector VARCHAR2(255),
	contador_prejardin_jardin INTEGER,
	contador_transicion INTEGER,
	contador_primaria INTEGER,
	contador_secundaria INTEGER,
	contador_media INTEGER,
	contador_adultos INTEGER,
	jornada_completa VARCHAR(8),
	jornada_manana VARCHAR(8),
	jornada_tarde VARCHAR(8),
	jornada_nocturna VARCHAR(8),
	jornada_fin_de_semana VARCHAR(8),
	jornada_unica VARCHAR(8),
	clasificacion_icfes VARCHAR(8)
);

ALTER TABLE colegios ADD CONSTRAINT COMUNA_FK FOREIGN KEY(comuna_id) REFERENCES COMUNAS(ID);


--Consulta 7.1
SELECT DISTINCT
    BARRIO
    ,COUNT(1) OVER(PARTITION BY BARRIO ) NUMERO_COLEGIOS
FROM 
    COLEGIOS A
INNER JOIN
    COMUNAS B
ON
    A.COMUNA_ID = B.ID
WHERE
    B.NOMBRE = 'BUENOS AIRES'
ORDER BY
    NUMERO_COLEGIOS DESC;



--7.2
SELECT
    A.ID
    ,A.NOMBRE_SEDE
    ,A.COMUNA_ID
    ,B.NOMBRE NOMBRE_COMUNA
    ,SUM(CONTADOR_PREJARDIN_JARDIN+CONTADOR_TRANSICION+CONTADOR_PRIMARIA+CONTADOR_SECUNDARIA+CONTADOR_MEDIA+CONTADOR_ADULTOS) OVER( ) TOTAL_GENERAL
    ,SUM(CONTADOR_PREJARDIN_JARDIN+CONTADOR_TRANSICION+CONTADOR_PRIMARIA+CONTADOR_SECUNDARIA+CONTADOR_MEDIA+CONTADOR_ADULTOS) OVER(PARTITION BY B.NOMBRE ) TOTAL_POR_COMUNA
FROM
    COLEGIOS A
LEFT JOIN
    COMUNAS B
ON 
    A.COMUNA_ID = B.ID
ORDER BY
    A.ID ASC;

--7.3

SELECT
    A.ID
    ,A.NOMBRE_SEDE
    ,A.COMUNA_ID
    ,B.NOMBRE NOMBRE_COMUNA
    ,CONTADOR_SECUNDARIA
    ,ROUND(AVG(CONTADOR_SECUNDARIA) OVER(PARTITION BY B.NOMBRE ),2) PROMEDIO_SECUNDARIA_COMUNA
FROM
    COLEGIOS A
LEFT JOIN
    COMUNAS B
ON 
    A.COMUNA_ID = B.ID
WHERE
    A.CONTADOR_PREJARDIN_JARDIN != 0
    AND A.SECTOR = 'No Oficial'
    AND B.NOMBRE IN ('ARANJUEZ','CASTILLA','DOCE DE OCTUBRE')
ORDER BY
    A.ID ASC;


--7.4

SELECT DISTINCT
    RECTOR   
    ,COUNT(1) OVER(PARTITION BY RECTOR ) NUMERO_COLEGIOS
FROM 
    COLEGIOS
WHERE
    RECTOR NOT LIKE '%@%'
    AND RECTOR != 's/d'
ORDER BY
    RECTOR;



SELECT DISTINCT CLASIFICACION_ICFES FROM COLEGIOS;

SELECT * FROM COMUNAS;

--7.5

SELECT 
    NOMBRE_SEDE
    ,BARRIO
    ,DIRECCION_SEDE
    ,CLASIFICACION_ICFES
FROM 
    COLEGIOS
WHERE
    ZONA IN ('Rural','rural')
    AND CLASIFICACION_ICFES != 'N/A'
    OR (CONTADOR_ADULTOS > 200
    OR CONTADOR_MEDIA > 200
    OR CONTADOR_PREJARDIN_JARDIN > 200
    OR CONTADOR_PRIMARIA > 200
    OR CONTADOR_SECUNDARIA > 200
    OR CONTADOR_TRANSICION > 200)
;

